### ISSUE TITLE
Example of usage as a python library needed

### ISSUE THREAD

**Issue by franpog859** [jaroslaw243/gt_im_s#1]
Hey! The project seems to be superb and really impactful! I want to use this library in my own project. I'd love to have it imported into my project as a normal python library

1. Is it possible to just load a static config and use it with an image to get an output mask? Something like this:
```py
import gt_im_s

gts = gt_im_s.load_config("default_config.yaml")
mask = gts.generate_mask(image)
```
Where the `default_config.yaml` file contains all the needed configs to run the mask generator, the input `image` is a `numpy.ndarray` with shape for example `(100, 150, 3)` which are the image dimensions and the three RGB canals, and the output `mask` is a similarly `(100,150)` shaped `numpy.ndarray` which contains `0` or `1` (or eventually `255`) values that correspond to the mask itself. If so, what the `default_config.yaml` should contain to work correctly on for example this image?
![image](https://user-images.githubusercontent.com/32485355/178263763-03bef7b5-3f34-4cf1-b3a3-b0b8c0915516.png)
___
2. I also want to ask if there is a possibility to use this library as mentioned above to remove hair from the image. So it's something like this:
```py
import gt_im_s

gts = gt_im_s.load_config("default_config.yaml")
image_without_hair = gts.remove_hair(image)
```
Where all the things are the same as previously and the `image_without_hair` is a `numpy.ndarray` with the `(100, 150, 3)` shape and the same structure as the input image

I'd love to have it working like this. If not, how can I make this project work smoothly and similarly to the two flows mentioned above?

**Comment by jaroslaw243** [comment]
1. I made some changes in the `game_theoretic_framework` class so it works as a library and added an script with example of such usage.
If you want an image to be stored as a numpy array then set `full_init` to `True` when creating the yaml file. I don't recommend it though, because storing images in a yaml file is inefficient. 
Colour images need to be converted to grayscale (it's done automatically when using `load_image`), because with that kind of images in mind whole algorithm was developed.

Example output:
![example_output](https://user-images.githubusercontent.com/63237911/178284521-3ff89366-6e08-4cfd-9236-a5a89f6492bf.png)

Yaml file used to acquire that output mask:
```YAML
!!python/object:game_theoretic_framework.GameTheoreticFramework
b_cost_interlaced: null
clique_size: 4
contours: null
differential_evolution_bounds_width: 0.55
expected_val_in: 1
expected_val_out: 0
image: null
image_gradient: null
image_path: .\obrazki_do_testow\IMD004\IMD004_Dermoscopic_Image\IMD004.bmp
img_gradient_ksize: 27
init_b_cost_interlaced: null
init_contours: .\obrazki_do_testow\IMD004\IMD004_lesion\IMD004_lesion.bmp
init_fourier_coeffs_first_part: null
init_fourier_coeffs_second_part: null
init_img_seg: null
init_tr: null
iter_num: 0
max_iterations: 3
object_brighter_than_background: false
order_of_fourier_coeffs: 14
p2c_acc: 2000
prior_b_cost: 0
region_segmentation: null
scaling_const_alpha: 0.1
scaling_const_beta: 0.1
sm_const: 14
```

2. In `utils` there is function `hair_removal` that removes hair from given image.
